version: 1
disable_existing_loggers: false

formatters:
  simple:
    format: "%(filename)s [%(levelname)s] %(message)s | %(asctime)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

root:
  level: DEBUG
  handlers: [console]
